[package]
name = "btree-ondisk"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
human_bytes = "0.4.3"
indicatif = "0.17"
atomic_refcell = "0.1.13"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = ["rc"]
rc = []
arc = []

[[example]]
name = "mt-rc"
path = "examples/mt-rc.rs"

[[example]]
name = "mt-arc"
path = "examples/mt-arc.rs"
required-features = ["arc"]
