[package]
name = "btree-ondisk"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
tokio = { version = "1", features = ["full"] }
human_bytes = "0.4.3"
