[package]
name = "btree-ondisk-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[features]
default = ["rc"]
rc = ["btree-ondisk/rc", "btree-ondisk/value-check", "btree-ondisk/tokio-runtime"]
arc = ["btree-ondisk/arc", "btree-ondisk/value-check", "btree-ondisk/tokio-runtime"]

[dependencies]
libfuzzer-sys = "0.4"
tokio = { version = "1", features = ["rt"] }

[dependencies.btree-ondisk]
path = ".."
default-features = false

[[bin]]
name = "btree_node_from_slice"
path = "fuzz_targets/btree_node_from_slice.rs"
test = false
doc = false
bench = false

[[bin]]
name = "direct_node_from_slice"
path = "fuzz_targets/direct_node_from_slice.rs"
test = false
doc = false
bench = false

[[bin]]
name = "bmap_read"
path = "fuzz_targets/bmap_read.rs"
test = false
doc = false
bench = false

[[bin]]
name = "bmap_ops"
path = "fuzz_targets/bmap_ops.rs"
test = false
doc = false
bench = false

[[bin]]
name = "bmap_lookup_batch"
path = "fuzz_targets/bmap_lookup_batch.rs"
test = false
doc = false
bench = false
